apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-deployment
  namespace: prisma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma-primary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: prisma-primary
    spec:
      containers:
        - name: prisma-primary
          image: prismagraphql/prisma-prod:1.17.2
          imagePullPolicy: Always
          resources: # CHANGE THIS AS NEEDED
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SLOW_QUERIES_LOGGING
              value: "true"
            - name: JAVA_OPTS
              value: "-Xmx800m" # CHANGE THIS AS NEEDED
            - name: ENV
              value: "prod"
            - name: PRISMA_CONFIG
              value: | # CHANGE THIS AS NEEDED
                port: 4466
                managementApiSecret: "MuchSecret"
                enableManagementApi: "true"
                server2serverSecret: "SuperSecretWow"
                rabbitUri: "amqp://<RABBIT_USER>:<RABBIT_USER_PASS>@rabbit-cluster-rabbitmq.rabbit.svc.cluster.local:5672"
                databases:
                  default:
                    connector: "mysql"
                    active: "true"
                    host: "<DB_HOST>"
                    port: "<DB_PORT>"
                    user: "<DB_USER>"
                    password: "<DB_PASS>"
                    connectionLimit: 20
                    database: "prisma"
                    managementSchema: "prisma"
                    ssl: false
          ports:
            - containerPort: 4466
---
apiVersion: v1
kind: Service
metadata:
  name: prisma-primary-service
  namespace: prisma
spec:
  selector: 
    app: prisma-primary
  type: ClusterIP
  ports:
    - name: http
      port: 4466
      targetPort: 4466
      protocol: TCP