apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: certificates
spec:
  acme:
    email: "<YOUR_CONTACT_MAIL>"
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    dns01:
      providers:
      - name: prod-clouddns
        route53:
          region: us-east-1 # It looks like this doesn't really matter.
          accessKeyID: "<YOUR_AWS_ACCESS_KEY_ID>"
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key
